### ISSUE TITLE
autosuggestions for coach types

### ISSUE THREAD

**Issue by icefisher225** [TG-Techie/CodeRypl#30]
add preloaded autosuggestions for the type field in coach tab

the common types of coaches:
head coach
assistant coach
associate coach
assistant head coach
associate head coach
athletic trainer
goalie coach
strength and conditioning coach

**Comment by TG-Techie** [comment]
I'd suggest subclassing this then adding a class var that is a `set()` of the suggestions. Then in the subclass  ` | ` that set with the one that is fetched from the file model.  (on line 74) or if you can think of a clearer|cleaner way to do it please do!
https://github.com/TG-Techie/CodeRypl/blob/2b058df5c73414e85b6c76d68ba0cd30c17386a5/code_rypl/table.py#L67-L79

then update where it is used for the coach.

**Comment by TG-Techie** [comment]
implemented a good bit ago
