### ISSUE TITLE
Create, build, and release on merge into main

### ISSUE THREAD

**Issue by icefisher225** [TG-Techie/CodeRypl#44]
https://github.com/marketplace/actions/create-release

**Comment by TG-Techie** [comment]
`git rev-parse --short main` to get the short commit hash

**Comment by TG-Techie** [comment]
So I did some exploration into this (the results can be found on the `auto-build-2` and `try_linux` branches. there are a few issue. One of which is that two runs cannot both send artifacts to a release (at least from brief encounter with the process). However building the apps via an action is totally do-able. So we could ship them over ftp *or something, I’m not the network human* to another location. Additionally, PyInstaller needs to run on the operating system the desired app should run on. but actions have the big three so I'm not concerned. 

The macos branch can work but the tagging sitch needs some work

**Comment by TG-Techie** [comment]
implemented fro main and any branch neds release for a macOS build

**Comment by icefisher225** [comment]
Oh, good evening. 

Best,

RFCB

Ryan Cheevers-Brown
CheevTech IT Services
Cheevers Photography
